name: Create the DEB
on: push

jobs:
  Create_Packages:
    name: Create Package Debian 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          dpkg-deb --build github.repository  package.deb

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: package.deb
