on:
  push:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          using: 'node20'
          main: 'main.js'

      - uses: singingwolfboy/build-dpkg-buster@v1
        id: build
        with:
          args:  ${{ github.repository }}

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ${{ steps.build.outputs.filename }}

